apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shortener
  template:
    metadata:
      labels:
        app: shortener
    spec:
      containers:
      - name: shortener
        image: strayca7/url-shortener:v0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config
            mountPath: /app/config.yaml
            subPath: config.yaml
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: shortener-config
          items:
          - key: config.yaml
            path: config.yaml  
