apiVersion: v1
kind: Service
metadata:
  name: shortener-nodeport
  namespace: devops
spec:
  selector:
    app: shortener
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8080
    nodePort: 30088
