apiVersion: v1
kind: ConfigMap
metadata:
  name: shortener-config
  namespace: devops
data:
  config.yaml: |
    jwt_secret: "secret"

    mysql:
      user: "root"
      password: "famcat777"
      host: "mysql.cat-devops.svc.cluster.local"
      port: "3306"
      database: "miniurl"

    pgsql:
      host: "localhost"
      port: "5432"
      user: "postgres"
      password: "your_password"
      database: "your_database"
      sslmode: "disable"
      timezone: "Asia/Shanghai"

    redis:
      host: "localhost"
      prot: "6379"
      password: "your_password"
      db: "0"