test_mode: true

# Config.yaml 不要集成在镜像中，应该用 ConfigMap 挂载到容器 /app/config.yaml 目录下
# Do not integrate Config.yaml into the image, you should mount ConfigMap to the container /app/config.yaml directory
jwt_secret: "secret"

mysql:
  user: "root"
  password: "famcat777"
  # 这里需要修改你的数据库地址，"127.0.0.1" 或者 "mysql.devops.svc.cluster.local"
  # Here you need to modify your database address, "127.0.0.1" or "mysql.devops.svc.cluster.local"
  # 如果你在 docker 中运行 shortener，host 需要改成 "host.docker.internal"，再用 -v ./config.yaml:/app/config.yaml 挂载。
  # If your shortener is running in docker container, host need to change to "host.docker.internal", then use -v ./config.yaml:/app/config.yaml mount.
  host: "localhost"
  port: "3306"
  database: "miniurl"

pgsql:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "your_password"
  database: "your_database"
  sslmode: "disable"
  timezone: "Asia/Shanghai"

redis:
  host: "localhost"
  prot: "6379"
  password: "your_password"
  db: "0"